package com.linksame.crm.erp.work.entity;

import com.linksame.crm.erp.work.entity.base.BaseTask;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task().dao();
	private List<Object>  Tasks;

	public List<Object> getTasks() {
		return Tasks;
	}

	public void setTasks(List<Object> tasks) {
		Tasks = tasks;
	}
}
