package com.linksame.crm.erp.work.entity;

import com.linksame.crm.erp.work.entity.base.BaseTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task().dao();
}
