package com.linksame.crm.erp.oa.entity;

import com.linksame.crm.erp.oa.entity.base.BaseOaAnnouncement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaAnnouncement extends BaseOaAnnouncement<OaAnnouncement> {
	public static final OaAnnouncement dao = new OaAnnouncement().dao();
}
