package com.linksame.crm.erp.pmp.entity;


import com.linksame.crm.erp.pmp.entity.base.BasePmpBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmpBusiness extends BasePmpBusiness<PmpBusiness> {
	public static final PmpBusiness dao = new PmpBusiness().dao();
}
