package com.linksame.crm.erp.pmp.entity;

import com.linksame.crm.erp.pmp.entity.base.BasePmpContractCardinalNumber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PmpContractCardinalNumber extends BasePmpContractCardinalNumber<PmpContractCardinalNumber> {
	public static final PmpContractCardinalNumber dao = new PmpContractCardinalNumber().dao();
}
