package com.linksame.crm.erp.admin.entity;

import com.linksame.crm.erp.admin.entity.base.BaseAdminFieldStyle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFieldStyle extends BaseAdminFieldStyle<AdminFieldStyle> {
	public static final AdminFieldStyle dao = new AdminFieldStyle().dao();
}
