package com.linksame.crm.erp.admin.entity;

import com.linksame.crm.erp.admin.entity.base.BaseAdminExamineStep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamineStep extends BaseAdminExamineStep<AdminExamineStep> {
	public static final AdminExamineStep dao = new AdminExamineStep().dao();
}
