package com.linksame.crm.erp.admin.entity;

import com.linksame.crm.erp.admin.entity.base.BaseAdminFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFile extends BaseAdminFile<AdminFile> {
	public static final AdminFile dao = new AdminFile().dao();
}
