package com.linksame.crm.erp.admin.entity;

import com.linksame.crm.erp.admin.entity.base.BaseAdminExamine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamine extends BaseAdminExamine<AdminExamine> {
	public static final AdminExamine dao = new AdminExamine().dao();
}
