package com.linksame.crm.erp.admin.entity;

import com.linksame.crm.erp.admin.entity.base.BaseCrmAchievement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmAchievement extends BaseCrmAchievement<CrmAchievement> {
	public static final CrmAchievement dao = new CrmAchievement().dao();
}
