package com.linksame.crm.erp.admin.entity;

import com.linksame.crm.erp.admin.entity.base.BaseAdminMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminMessage extends BaseAdminMessage<AdminMessage> {
    public static final AdminMessage dao = new AdminMessage().dao();
}
