package com.linksame.crm.erp.admin.entity;

import com.linksame.crm.erp.admin.entity.base.BaseAdminExamineRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamineRecord extends BaseAdminExamineRecord<AdminExamineRecord> {
	public static final AdminExamineRecord dao = new AdminExamineRecord().dao();
}
