package com.linksame.crm.erp.work.entity;

import com.linksame.crm.erp.work.entity.base.BaseWorkTaskLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkTaskLog extends BaseWorkTaskLog<WorkTaskLog> {
	public static final WorkTaskLog dao = new WorkTaskLog().dao();
}
