package com.linksame.crm.erp.crm.entity;

import com.linksame.crm.erp.crm.entity.base.BaseCrmActionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmActionRecord extends BaseCrmActionRecord<CrmActionRecord> {
	public static final CrmActionRecord dao = new CrmActionRecord().dao();
}
