package com.linksame.crm.erp.crm.entity;

import com.linksame.crm.erp.crm.entity.base.BaseCrmBusinessProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessProduct extends BaseCrmBusinessProduct<CrmBusinessProduct> {
	public static final CrmBusinessProduct dao = new CrmBusinessProduct().dao();
}
