package com.linksame.crm.erp.crm.entity;

import com.linksame.crm.erp.crm.entity.base.BaseCrmContactsBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmContactsBusiness extends BaseCrmContactsBusiness<CrmContactsBusiness> {
    public static final CrmContactsBusiness dao = new CrmContactsBusiness().dao();
}
