package com.linksame.crm.erp.crm.entity;

import com.linksame.crm.erp.crm.entity.base.BaseCrmCustomerSettingUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("seial")
public class CrmCustomerSettingUser extends BaseCrmCustomerSettingUser<CrmCustomerSettingUser> {
	public static final CrmCustomerSettingUser dao = new CrmCustomerSettingUser().dao();
}
