package com.linksame.crm.erp.pmp.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmpBusiness<M extends BasePmpBusiness<M>> extends Model<M> implements IBean {

    public void setBusinessId(java.lang.Long businessId) {
        set("business_id", businessId);
    }

    public java.lang.Long getBusinessId() {
        return getLong("business_id");
    }

    public void setObjectId(java.lang.Long objectId) {
        set("object_id", objectId);
    }

    public java.lang.Long getObjectId() {
        return getLong("object_id");
    }

    public void setCorrelationId(java.lang.Long correlationId) {
        set("correlation_id", correlationId);
    }

    public java.lang.Long getCorrelationId() {
        return getLong("correlation_id");
    }

    public void setObjectType(java.lang.Integer objectType) {
        set("object_type", objectType);
    }

    public java.lang.Integer getObjectType() {
        return getInt("object_type");
    }

    public void setCorrelationType(java.lang.Integer correlationType) {
        set("correlation_type", correlationType);
    }

    public java.lang.Integer getCorrelationType() {
        return getInt("correlation_type");
    }

}
