package com.linksame.crm.erp.pmp.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmpContractCardinalNumber<M extends BasePmpContractCardinalNumber<M>> extends Model<M> implements IBean {

	public void setCardinalNumberId(Long cardinalNumberId) {
		set("cardinal_number_id", cardinalNumberId);
	}
	
	public Long getCardinalNumberId() {
		return getLong("cardinal_number_id");
	}

	public void setContractId(Long contractId) {
		set("contract_id", contractId);
	}
	
	public Long getContractId() {
		return getLong("contract_id");
	}

	public void setCardinalNumberName(String cardinalNumberName) {
		set("cardinal_number_name", cardinalNumberName);
	}
	
	public String getCardinalNumberName() {
		return getStr("cardinal_number_name");
	}

	public void setCardinalNumberIndexe(Long cardinalNumberIndexe) {
		set("cardinal_number_indexe", cardinalNumberIndexe);
	}
	
	public Long getCardinalNumberIndexe() {
		return getLong("cardinal_number_indexe");
	}

	public void setCardinalNumberPercentage(Integer cardinalNumberPercentage) {
		set("cardinal_number_percentage", cardinalNumberPercentage);
	}
	
	public Integer getCardinalNumberPercentage() {
		return getInt("cardinal_number_percentage");
	}

	public void setCardinalNumberMoney(java.math.BigDecimal cardinalNumberMoney) {
		set("cardinal_number_money", cardinalNumberMoney);
	}
	
	public java.math.BigDecimal getCardinalNumberMoney() {
		return get("cardinal_number_money");
	}

}
